import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
	const applicants = await prisma.applicant.createMany({
		data: [
			{
				applicantNumber: "0001",
				gender: "M",
				title: "Mr.",
				firstName: "John",
				lastName: "Doe",
				nickName: "Johnny",
				birthDate: "01-01-2000",
				street: "Main Street",
				number: "1",
				numberExtension: "A",
				zipCode: "1234AB",
				place: "Amsterdam",
				applicantkey: "123456789",
				isActive: true,
				description: "This is a description",
			},
			{
				applicantNumber: "0002",
				gender: "F",
				title: "Mrs.",
				firstName: "Jane",
				lastName: "Doe",
				nickName: "Janny",
				birthDate: "01-01-2000",
				street: "Main Street",
				number: "1",
				numberExtension: "A",
				zipCode: "1234AB",
				place: "Amsterdam",
				applicantkey: "123456789",
				isActive: true,
				description: "This is a description",
			},
			{
				applicantNumber: "0003",
				gender: "M",
				title: "Mr.",
				firstName: "bob",
				lastName: "Doe",
				nickName: "bobby",
				birthDate: "01-01-2000",
				street: "Main Street",
				number: "1",
				numberExtension: "A",
				zipCode: "1234AB",
				place: "Amsterdam",
				applicantkey: "123456789",
				isActive: true,
				description: "This is a description",
			},
			{
				applicantNumber: "0004",
				gender: "F",
				title: "Mrs.",
				firstName: "Sally",
				lastName: "Doe",
				nickName: "Sally",
				birthDate: "01-01-2000",
				street: "Main Street",
				number: "1",
				numberExtension: "A",
				zipCode: "1234AB",
				place: "Amsterdam",
				applicantkey: "123456789",
				isActive: true,
				description: "This is a description",
			},
			{
				applicantNumber: "0005",
				gender: "M",
				title: "Mr.",
				firstName: "George",
				lastName: "Doe",
				nickName: "George",
				birthDate: "01-01-2000",
				street: "Main Street",
				number: "1",
				numberExtension: "A",
				zipCode: "1234AB",
				place: "Amsterdam",
				applicantkey: "123456789",
				isActive: true,
				description: "This is a description",
			},
		],
	});
	console.log(applicants);
}

main();
